<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>ChessLibbyMrNaniii</PackageId>
    <Version>1.0.1</Version>
    <Authors>MrNaniii</Authors>
    <Description>Chess engine.</Description>
    <Tags>csharp;library;</Tags>
  </PropertyGroup>

</Project>